version: '3.8'

services:
  db:
    image: postgres:13
    container_name: fastapi_app_postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: secure_password123!
      POSTGRES_DB: fastapi_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
