"""Add status field to Post model

Revision ID: de2822dbd4ca
Revises: 005795c729fb
Create Date: 2024-11-13 19:04:19.619567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2822dbd4ca'
down_revision: Union[str, None] = '005795c729fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
